import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * administrator.java
 *
 * Created on Sep 4, 2010, 3:52:05 PM
 */

/**
 *
 * @author Administrator
 */
public class administrator extends javax.swing.JFrame {
DefaultTableModel tm =null;
Connection con = null;
Statement stmt=null;
ResultSet rs=null;

    /** Creates new form administrator */
    public administrator() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usertable = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_record = new javax.swing.JTable();
        uback = new javax.swing.JButton();
        clienttable = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        client_record = new javax.swing.JTable();
        cback = new javax.swing.JButton();
        transactiontable = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        transaction = new javax.swing.JTable();
        tback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JButton();
        client = new javax.swing.JButton();
        tranc = new javax.swing.JButton();

        usertable.setTitle("User Details");
        usertable.setMinimumSize(new java.awt.Dimension(1000, 250));
        usertable.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                usertableWindowActivated(evt);
            }
        });

        user_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "DATE OF BIRTH", "AGE", "GENDER", "PROFESSION", "UID/PAN", "USER ID", "PASSWORD", "EMAIL ID", "PHONE NO."
            }
        ));
        jScrollPane1.setViewportView(user_record);

        uback.setText("back");
        uback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usertableLayout = new javax.swing.GroupLayout(usertable.getContentPane());
        usertable.getContentPane().setLayout(usertableLayout);
        usertableLayout.setHorizontalGroup(
            usertableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usertableLayout.createSequentialGroup()
                .addGroup(usertableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usertableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE))
                    .addGroup(usertableLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(uback)))
                .addContainerGap())
        );
        usertableLayout.setVerticalGroup(
            usertableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usertableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(uback)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        clienttable.setTitle("Client Details");
        clienttable.setMinimumSize(new java.awt.Dimension(1000, 150));
        clienttable.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                clienttableWindowActivated(evt);
            }
        });

        client_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "NAME OF ORGANISATION", "ADDRESS", "DESIGNATION", "USER ID", "PASSWORD", "EMAIL ID", "PHONE NO", "CR NO."
            }
        ));
        jScrollPane2.setViewportView(client_record);

        cback.setText("Back");
        cback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clienttableLayout = new javax.swing.GroupLayout(clienttable.getContentPane());
        clienttable.getContentPane().setLayout(clienttableLayout);
        clienttableLayout.setHorizontalGroup(
            clienttableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienttableLayout.createSequentialGroup()
                .addGroup(clienttableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clienttableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                    .addGroup(clienttableLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(cback)))
                .addContainerGap())
        );
        clienttableLayout.setVerticalGroup(
            clienttableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienttableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cback)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        transactiontable.setTitle("Transaction details");
        transactiontable.setMinimumSize(new java.awt.Dimension(1100, 250));
        transactiontable.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                transactiontableWindowActivated(evt);
            }
        });

        transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "reciept no", "amount", "npr", "sch", "off", "mag", "parts", "home", "mobiles", "machinery", "cds", "battery", "tables", "sofa", "cupboards", "beds", "glass", "poly", "milk", "utensils", "office", "alu", "iron", "copper", "steel"
            }
        ));
        jScrollPane3.setViewportView(transaction);

        tback.setText("Back");
        tback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactiontableLayout = new javax.swing.GroupLayout(transactiontable.getContentPane());
        transactiontable.getContentPane().setLayout(transactiontableLayout);
        transactiontableLayout.setHorizontalGroup(
            transactiontableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactiontableLayout.createSequentialGroup()
                .addGroup(transactiontableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactiontableLayout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(tback, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactiontableLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)))
                .addContainerGap())
        );
        transactiontableLayout.setVerticalGroup(
            transactiontableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactiontableLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tback)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrator");
        setMinimumSize(new java.awt.Dimension(500, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("WELCOME ADMINISTRATOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 360, 40);

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Return to home");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 290, 142, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("your current profits are"));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 70, 140, 60);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tables"));

        user.setText("user table");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        client.setText("client table");
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });

        tranc.setText("transaction table");
        tranc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trancActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(user)
                        .addGap(55, 55, 55)
                        .addComponent(client))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(tranc)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user)
                    .addComponent(client))
                .addGap(18, 18, 18)
                .addComponent(tranc)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 150, 300, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
usertable.setVisible(true);
dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
clienttable.setVisible(true);
dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_clientActionPerformed

    private void usertableWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_usertableWindowActivated
 tm=(DefaultTableModel)user_record.getModel();

        try{ Class.forName("java.sql.Driver");
    con =  DriverManager.getConnection("jdbc:mysql://localhost/ip_project12","root","");
  stmt =con.createStatement();
 String query = "select * from user_record;";
 rs = stmt.executeQuery(query);
 while(rs.next()){
     tm.addRow(new Object[]{
         rs.getString(1),rs.getString(2),rs.getDate(3),rs.getInt(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getLong(11)
     });
 }
 rs.close();
 stmt.close();
 con.close();






 }
 catch(Exception e){
     JOptionPane.showMessageDialog(null, "error:"+e.getMessage());
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_usertableWindowActivated

    private void clienttableWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_clienttableWindowActivated
  tm=(DefaultTableModel)client_record.getModel();

        try{   Class.forName("java.sql.Driver");
    con =  DriverManager.getConnection("jdbc:mysql://localhost/ip_project12","root","");
  stmt =con.createStatement();
 String query = "select * from client_record;";
 rs = stmt.executeQuery(query);
 while(rs.next()){
     tm.addRow(new Object[]{
         rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8),rs.getString(9)
     });
 }
 rs.close();
 stmt.close();
 con.close();

System.out.println("ok");




 }
 catch(Exception e){
     JOptionPane.showMessageDialog(null, "error:"+e.getMessage());
 }       // TODO add your handling code here:
    }//GEN-LAST:event_clienttableWindowActivated

    private void transactiontableWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_transactiontableWindowActivated
 tm=(DefaultTableModel)transaction.getModel();

        try{   Class.forName("java.sql.Driver");
    con =  DriverManager.getConnection("jdbc:mysql://localhost/ip_project12","root","");
  stmt =con.createStatement();
 String query = "select * from transaction;";
 rs = stmt.executeQuery(query);
while(rs.next()){
     
  Object a[] ={rs.getString(1),rs.getInt(2),rs.getInt(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7),rs.getInt(8),rs.getInt(9),rs.getInt(10),rs.getInt(11),rs.getInt(12),rs.getInt(13),rs.getInt(14),rs.getInt(15),rs.getInt(16),rs.getInt(17),rs.getInt(18),rs.getInt(19),rs.getInt(20),rs.getInt(21),rs.getInt(22),rs.getInt(23),rs.getInt(24),rs.getInt(25),rs.getInt(26)};
tm.addRow(a);
}
 rs.close();
 stmt.close();
 con.close();






 }
 catch(Exception e){
     JOptionPane.showMessageDialog(null, "error:"+e.getMessage());
 }        // TODO add your handling code here:
    }//GEN-LAST:event_transactiontableWindowActivated

    private void trancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trancActionPerformed
transactiontable.setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_trancActionPerformed

    private void ubackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubackActionPerformed
administrator z = new administrator();
z.setVisible(true);
usertable.setVisible(false);
       this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_ubackActionPerformed

    private void cbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbackActionPerformed
    administrator f = new administrator();
f.setVisible(true);
clienttable.setVisible(false);

           // TODO add your handling code here:
    }//GEN-LAST:event_cbackActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    homepage q = new homepage();
    q.setVisible(true);
    dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbackActionPerformed
 administrator f = new administrator();
f.setVisible(true);
transactiontable.setVisible(false);
       this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_tbackActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    try{
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/ip_project12","root","");
        stmt=con.createStatement();
        String query="select sum(amount) from transaction;";
        rs=stmt.executeQuery(query);
        rs.first();
    jLabel4.setText("Rs:   "+rs.getString(1));
       
    }

    catch(Exception e){

    }
    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cback;
    private javax.swing.JButton client;
    private javax.swing.JTable client_record;
    private javax.swing.JFrame clienttable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton tback;
    private javax.swing.JButton tranc;
    private javax.swing.JTable transaction;
    private javax.swing.JFrame transactiontable;
    private javax.swing.JButton uback;
    private javax.swing.JButton user;
    private javax.swing.JTable user_record;
    private javax.swing.JFrame usertable;
    // End of variables declaration//GEN-END:variables

}
