
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Random;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * client_workspace.java
 *
 * Created on Sep 6, 2002, 2:04:03 PM
 */

/**
 *
 * @author students
 */
public class client_workspace extends javax.swing.JFrame {
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
DefaultTableModel tm =null;
rates st=new rates();
client_login abc = new client_login();

    /** Creates new form client_workspace */
    public client_workspace() {
        try{
            Class.forName("java.sql.Driver");

        con=DriverManager.getConnection("jdbc:mysql://localHost/ip_project12","root","");
        System.out.println("connection established");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        task = new javax.swing.JFrame();
        placeorder1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        paper = new javax.swing.JPanel();
        npr_txt = new javax.swing.JTextField();
        maglbl = new javax.swing.JLabel();
        schlbl = new javax.swing.JLabel();
        offlbl = new javax.swing.JLabel();
        nprlbl = new javax.swing.JLabel();
        mag_txt = new javax.swing.JTextField();
        sch_txt = new javax.swing.JTextField();
        off_txt = new javax.swing.JTextField();
        eWaste = new javax.swing.JPanel();
        battery_txt = new javax.swing.JTextField();
        machinery_txt = new javax.swing.JTextField();
        mobiles_txt = new javax.swing.JTextField();
        parts_txt = new javax.swing.JTextField();
        cds_txt = new javax.swing.JTextField();
        home_txt = new javax.swing.JTextField();
        homelbl = new javax.swing.JLabel();
        batterylbl = new javax.swing.JLabel();
        machinerylbl = new javax.swing.JLabel();
        cdslbl = new javax.swing.JLabel();
        partslbl = new javax.swing.JLabel();
        mobileslbl = new javax.swing.JLabel();
        furniture = new javax.swing.JPanel();
        cupboards_txt = new javax.swing.JTextField();
        sofa_txt = new javax.swing.JTextField();
        tables_txt = new javax.swing.JTextField();
        beds_txt = new javax.swing.JTextField();
        glass_txt = new javax.swing.JTextField();
        cupboardslbl = new javax.swing.JLabel();
        bedslbl = new javax.swing.JLabel();
        glasslbl = new javax.swing.JLabel();
        sofalbl = new javax.swing.JLabel();
        tableslbl = new javax.swing.JLabel();
        plastics = new javax.swing.JPanel();
        poly_txt = new javax.swing.JTextField();
        milk_txt = new javax.swing.JTextField();
        utensils_txt = new javax.swing.JTextField();
        office_txt = new javax.swing.JTextField();
        utensilslbl = new javax.swing.JLabel();
        officelbl = new javax.swing.JLabel();
        milklbl = new javax.swing.JLabel();
        polylbl = new javax.swing.JLabel();
        metals = new javax.swing.JPanel();
        copper_txt = new javax.swing.JTextField();
        alu_txt = new javax.swing.JTextField();
        steel_txt = new javax.swing.JTextField();
        iron_txt = new javax.swing.JTextField();
        copperlbl = new javax.swing.JLabel();
        ironlbl = new javax.swing.JLabel();
        alulbl = new javax.swing.JLabel();
        steellbl = new javax.swing.JLabel();
        transaction = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        client_table = new javax.swing.JTable();
        placeorder_btn = new javax.swing.JButton();
        calc_btn = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        currentstocks = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        ulbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        place = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        current = new javax.swing.JButton();
        clbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();

        task.setMinimumSize(new java.awt.Dimension(750, 700));

        placeorder1.setText("PLACE ORDER");
        placeorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeorder1ActionPerformed(evt);
            }
        });

        back.setForeground(new java.awt.Color(51, 102, 255));
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        paper.setBorder(javax.swing.BorderFactory.createTitledBorder("PAPER"));

        npr_txt.setText("0");
        npr_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npr_txtActionPerformed(evt);
            }
        });
        npr_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                npr_txtFocusLost(evt);
            }
        });

        maglbl.setText("Magazine");

        schlbl.setText("School Sta");

        offlbl.setText("Office Sta");

        nprlbl.setText("News Paper");

        mag_txt.setText("0");
        mag_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mag_txtActionPerformed(evt);
            }
        });
        mag_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mag_txtFocusLost(evt);
            }
        });

        sch_txt.setText("0");
        sch_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sch_txtFocusLost(evt);
            }
        });

        off_txt.setText("0");
        off_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                off_txtFocusLost(evt);
            }
        });

        javax.swing.GroupLayout paperLayout = new javax.swing.GroupLayout(paper);
        paper.setLayout(paperLayout);
        paperLayout.setHorizontalGroup(
            paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paperLayout.createSequentialGroup()
                        .addComponent(nprlbl)
                        .addGap(18, 18, 18)
                        .addComponent(npr_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addGroup(paperLayout.createSequentialGroup()
                        .addComponent(maglbl)
                        .addGap(18, 18, 18)
                        .addComponent(mag_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(paperLayout.createSequentialGroup()
                        .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schlbl)
                            .addComponent(offlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(off_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(sch_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addContainerGap())
        );
        paperLayout.setVerticalGroup(
            paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paperLayout.createSequentialGroup()
                .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nprlbl))
                .addGap(18, 18, 18)
                .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maglbl)
                    .addComponent(mag_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schlbl)
                    .addComponent(sch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offlbl)
                    .addComponent(off_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        eWaste.setBorder(javax.swing.BorderFactory.createTitledBorder("eWASTE"));

        battery_txt.setText("0");
        battery_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                battery_txtFocusLost(evt);
            }
        });
        eWaste.add(battery_txt);

        machinery_txt.setText("0");
        machinery_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                machinery_txtFocusLost(evt);
            }
        });
        eWaste.add(machinery_txt);

        mobiles_txt.setText("0");
        mobiles_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobiles_txtFocusLost(evt);
            }
        });
        eWaste.add(mobiles_txt);

        parts_txt.setText("0");
        parts_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parts_txtActionPerformed(evt);
            }
        });
        parts_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                parts_txtFocusLost(evt);
            }
        });
        eWaste.add(parts_txt);

        cds_txt.setText("0");
        cds_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cds_txtFocusLost(evt);
            }
        });
        eWaste.add(cds_txt);

        home_txt.setText("0");
        home_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                home_txtFocusLost(evt);
            }
        });
        eWaste.add(home_txt);

        homelbl.setText("Home Apps");
        eWaste.add(homelbl);

        batterylbl.setText("Battery");
        eWaste.add(batterylbl);

        machinerylbl.setText("Machichery");
        eWaste.add(machinerylbl);

        cdslbl.setText("Cds");
        eWaste.add(cdslbl);

        partslbl.setText("parts");
        eWaste.add(partslbl);

        mobileslbl.setText("Mobiles");
        eWaste.add(mobileslbl);

        furniture.setBorder(javax.swing.BorderFactory.createTitledBorder("FURNITURE"));

        cupboards_txt.setText("0");
        cupboards_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cupboards_txtFocusLost(evt);
            }
        });

        sofa_txt.setText("0");
        sofa_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sofa_txtFocusLost(evt);
            }
        });

        tables_txt.setText("0");
        tables_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tables_txtFocusLost(evt);
            }
        });

        beds_txt.setText("0");
        beds_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                beds_txtFocusLost(evt);
            }
        });

        glass_txt.setText("0");
        glass_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                glass_txtFocusLost(evt);
            }
        });

        cupboardslbl.setText("cupboards");

        bedslbl.setText("Beds");

        glasslbl.setText("Glass");

        sofalbl.setText("Sofa");

        tableslbl.setText("tables");

        javax.swing.GroupLayout furnitureLayout = new javax.swing.GroupLayout(furniture);
        furniture.setLayout(furnitureLayout);
        furnitureLayout.setHorizontalGroup(
            furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, furnitureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cupboardslbl)
                    .addComponent(bedslbl)
                    .addComponent(glasslbl)
                    .addComponent(sofalbl)
                    .addComponent(tableslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(glass_txt)
                    .addComponent(cupboards_txt)
                    .addComponent(beds_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(sofa_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tables_txt))
                .addContainerGap())
        );
        furnitureLayout.setVerticalGroup(
            furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(furnitureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cupboards_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupboardslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beds_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glasslbl)
                    .addComponent(glass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sofa_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sofalbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(furnitureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tables_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableslbl))
                .addContainerGap())
        );

        plastics.setBorder(javax.swing.BorderFactory.createTitledBorder("PLASTICS"));

        poly_txt.setText("0");
        poly_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                poly_txtFocusLost(evt);
            }
        });

        milk_txt.setText("0");
        milk_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                milk_txtFocusLost(evt);
            }
        });

        utensils_txt.setText("0");
        utensils_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                utensils_txtFocusLost(evt);
            }
        });

        office_txt.setText("0");
        office_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                office_txtFocusLost(evt);
            }
        });

        utensilslbl.setText("Utensils");

        officelbl.setText("Office Furniture");

        milklbl.setText("milk bags");

        polylbl.setText("PolyBags");

        javax.swing.GroupLayout plasticsLayout = new javax.swing.GroupLayout(plastics);
        plastics.setLayout(plasticsLayout);
        plasticsLayout.setHorizontalGroup(
            plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plasticsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, plasticsLayout.createSequentialGroup()
                        .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polylbl)
                            .addComponent(milklbl))
                        .addGap(36, 36, 36)
                        .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plasticsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(poly_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(milk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plasticsLayout.createSequentialGroup()
                        .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, plasticsLayout.createSequentialGroup()
                                .addComponent(officelbl)
                                .addGap(18, 18, 18)
                                .addComponent(office_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plasticsLayout.createSequentialGroup()
                                .addComponent(utensilslbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(utensils_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addGap(36, 36, 36))
        );
        plasticsLayout.setVerticalGroup(
            plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plasticsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utensilslbl)
                    .addComponent(utensils_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officelbl)
                    .addComponent(office_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(milk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milklbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(plasticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(polylbl)
                    .addComponent(poly_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        metals.setBorder(javax.swing.BorderFactory.createTitledBorder("METALS"));

        copper_txt.setText("0");
        copper_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                copper_txtFocusLost(evt);
            }
        });

        alu_txt.setText("0");
        alu_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alu_txtFocusLost(evt);
            }
        });

        steel_txt.setText("0");
        steel_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                steel_txtFocusLost(evt);
            }
        });

        iron_txt.setText("0");
        iron_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                iron_txtFocusLost(evt);
            }
        });

        copperlbl.setText("Copper");

        ironlbl.setText("Iron");

        alulbl.setText("Aluminium");

        steellbl.setText("Steel");

        javax.swing.GroupLayout metalsLayout = new javax.swing.GroupLayout(metals);
        metals.setLayout(metalsLayout);
        metalsLayout.setHorizontalGroup(
            metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, metalsLayout.createSequentialGroup()
                        .addComponent(steellbl)
                        .addGap(23, 23, 23))
                    .addComponent(alulbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(copperlbl)
                        .addComponent(ironlbl)))
                .addGroup(metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(metalsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(metalsLayout.createSequentialGroup()
                                .addComponent(copper_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(metalsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(steel_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(iron_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, metalsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alu_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        metalsLayout.setVerticalGroup(
            metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(metalsLayout.createSequentialGroup()
                        .addComponent(copper_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iron_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(alu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(metalsLayout.createSequentialGroup()
                        .addComponent(copperlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ironlbl)
                        .addGap(18, 18, 18)
                        .addComponent(alulbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(metalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(steellbl))
                .addContainerGap())
        );

        javax.swing.GroupLayout taskLayout = new javax.swing.GroupLayout(task.getContentPane());
        task.getContentPane().setLayout(taskLayout);
        taskLayout.setHorizontalGroup(
            taskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(furniture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(metals, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(back))
            .addGroup(taskLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(eWaste, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(plastics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(placeorder1))
        );
        taskLayout.setVerticalGroup(
            taskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskLayout.createSequentialGroup()
                .addGroup(taskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(furniture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(taskLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(back)))
                .addGroup(taskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eWaste, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(taskLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(plastics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taskLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(placeorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        transaction.setMinimumSize(new java.awt.Dimension(700, 700));
        transaction.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                transactionWindowActivated(evt);
            }
        });
        transaction.getContentPane().setLayout(null);

        client_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMMODITY", "QUANTITY", "RATE", "AMOUNT"
            }
        ));
        jScrollPane2.setViewportView(client_table);

        transaction.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(5, 5, 452, 110);

        placeorder_btn.setText("PLACE ORDER");
        placeorder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeorder_btnActionPerformed(evt);
            }
        });
        transaction.getContentPane().add(placeorder_btn);
        placeorder_btn.setBounds(350, 150, 101, 23);

        calc_btn.setText("GRAND TOTAL");
        calc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_btnActionPerformed(evt);
            }
        });
        transaction.getContentPane().add(calc_btn);
        calc_btn.setBounds(40, 160, 103, 23);

        total.setBorder(javax.swing.BorderFactory.createTitledBorder("TOTAL"));
        transaction.getContentPane().add(total);
        total.setBounds(166, 150, 80, 30);

        currentstocks.setForeground(new java.awt.Color(102, 102, 255));
        currentstocks.setText("Current Stocks");
        currentstocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentstocksMouseClicked(evt);
            }
        });
        transaction.getContentPane().add(currentstocks);
        currentstocks.setBounds(250, 230, 71, 14);

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        transaction.getContentPane().add(clear);
        clear.setBounds(40, 210, 65, 23);
        transaction.getContentPane().add(ulbl);
        ulbl.setBounds(843, 216, 0, 0);

        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("LOGOUT");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        transaction.getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 230, 41, 14);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Client Workspace");
        setMinimumSize(new java.awt.Dimension(900, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        cs.setText("CURRENT STOCKS");
        cs.setEnabled(false);
        getContentPane().add(cs);
        cs.setBounds(330, 170, 220, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "paper", "sch", "off", "mag", "parts", "home", "mobile", "machinery", "cds", "battery", "table", "sofa", "cupboard", "beds", "glass", "poly", "milk", "utensils", "office", "alu", "iron", "copper", "steel"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 880, 120);

        place.setText("PLACE ORDER");
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });
        getContentPane().add(place);
        place.setBounds(100, 460, 170, 30);

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 10, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel4.setText("CLIENT WORKSPACE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 110, 290, 50);

        current.setText("Current Stocks");
        current.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentActionPerformed(evt);
            }
        });
        getContentPane().add(current);
        current.setBounds(450, 460, 170, 30);

        clbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        clbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(clbl);
        clbl.setBounds(30, 30, 110, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/REcyclone2.JPG"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 10, 120, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasks"));

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("PAPER");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("METALS");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("FURNITURE");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("E-WASTE");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("PLASTICS");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox5ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 380, 690, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
task.setVisible(true);
this.dispose();



       // TODO add your handling code here:
    }//GEN-LAST:event_placeActionPerformed

    private void parts_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parts_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parts_txtActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
client_workspace a =new client_workspace();
a.setVisible(true);

task.dispose();



// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
if (evt.getStateChange()==1){
   
    paper.setVisible(true);
   
}
else if (evt.getStateChange()==2){
  paper.setVisible(false);

}

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
if (evt.getStateChange()==1){

    eWaste.setVisible(true);

}
else if (evt.getStateChange()==2){
 eWaste.setVisible(false);

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
if (evt.getStateChange()==1){

  plastics.setVisible(true);

}
else if (evt.getStateChange()==2){
 plastics.setVisible(false);

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
if (evt.getStateChange()==1){

    metals.setVisible(true);

}
else if (evt.getStateChange()==2){
  metals.setVisible(false);

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void npr_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npr_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npr_txtActionPerformed

    private void currentstocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentstocksMouseClicked
client_workspace tt=new client_workspace();
tt.setVisible(true);


transaction.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_currentstocksMouseClicked

    private void transactionWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_transactionWindowActivated
   ulbl.setText(Login_Form.a);

        tm=(DefaultTableModel)client_table.getModel();

        try{
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localHost/ip_project12","root","");
        System.out.println("connection established");

Object a1[]={nprlbl.getText(),npr_txt.getText(),st.snpr,Integer.parseInt(npr_txt.getText())*st.snpr};
Object a2[]={schlbl.getText(),sch_txt.getText(),st.ssch,Integer.parseInt(sch_txt.getText())*st.ssch};
Object a3[]={offlbl.getText(),off_txt.getText(),st.soff,Integer.parseInt(off_txt.getText())*st.soff};
Object a4[]={maglbl.getText(),mag_txt.getText(),st.smag,Integer.parseInt(mag_txt.getText())*st.smag};
Object a5[]={partslbl.getText(),parts_txt.getText(),st.sparts,Integer.parseInt(parts_txt.getText())*st.sparts};
Object a6[]={batterylbl.getText(),battery_txt.getText(),st.sbattery,Integer.parseInt(battery_txt.getText())*st.sbattery};
Object a7[]={cdslbl.getText(),cds_txt.getText(),st.scds,Integer.parseInt(cds_txt.getText())*st.scds};
Object a8[]={machinerylbl.getText(),machinery_txt.getText(),st.smachinery,Integer.parseInt(machinery_txt.getText())*st.smachinery};
Object a9[]={homelbl.getText(),home_txt.getText(),st.shome,Integer.parseInt(home_txt.getText())*st.shome};
Object a10[]={tableslbl.getText(),tables_txt.getText(),st.stable,Integer.parseInt(tables_txt.getText())*st.stable};
Object a11[]={sofalbl.getText(),sofa_txt.getText(),st.ssofa,Integer.parseInt(sofa_txt.getText())*st.ssofa};
Object a12[]={cupboardslbl.getText(),cupboards_txt.getText(),st.scupboard,Integer.parseInt(cupboards_txt.getText())*st.scupboard};
Object a13[]={bedslbl.getText(),beds_txt.getText(),st.sbeds,Integer.parseInt(beds_txt.getText())*st.sbeds};
Object a14[]={glasslbl.getText(),glass_txt.getText(),st.sglass,Integer.parseInt(glass_txt.getText())*st.sglass};
Object a15[]={officelbl.getText(),office_txt.getText(),st.soffice,Integer.parseInt(office_txt.getText())*st.soffice};
Object a16[]={milklbl.getText(),milk_txt.getText(),st.smilk,Integer.parseInt(milk_txt.getText())*st.smilk};
Object a17[]={polylbl.getText(),poly_txt.getText(),st.spoly,Integer.parseInt(poly_txt.getText())*st.spoly};
Object a18[]={utensilslbl.getText(),utensils_txt.getText(),st.sutensils,Integer.parseInt(utensils_txt.getText())*st.sutensils};
Object a19[]={alulbl.getText(),alu_txt.getText(),st.salu,Integer.parseInt(alu_txt.getText())*st.salu};
Object a20[]={ironlbl.getText(),iron_txt.getText(),st.siron,Integer.parseInt(iron_txt.getText())*st.siron};
Object a21[]={copperlbl.getText(),copper_txt.getText(),st.scopper,Integer.parseInt(copper_txt.getText())*st.scopper};
Object a22[]={steellbl.getText(),steel_txt.getText(),st.ssteel,Integer.parseInt(steel_txt.getText())*st.ssteel};
Object a23[]={mobileslbl.getText(),mobiles_txt.getText(),st.smobile,Integer.parseInt(mobiles_txt.getText())*st.smobile};
tm.addRow(a1);
tm.addRow(a2);
tm.addRow(a3);
tm.addRow(a4);
tm.addRow(a5);
tm.addRow(a6);
tm.addRow(a7);
tm.addRow(a8);
tm.addRow(a9);
tm.addRow(a10);
tm.addRow(a11);
tm.addRow(a12);
tm.addRow(a13);
tm.addRow(a14);
tm.addRow(a15);
tm.addRow(a16);
tm.addRow(a17);
tm.addRow(a18);
tm.addRow(a19);
tm.addRow(a20);
tm.addRow(a21);
tm.addRow(a22);
tm.addRow(a23);

int j=tm.getRowCount();
int i;
for(i=j-1;i>=0;--i){
if (Double.parseDouble(tm.getValueAt(i,3).toString())==0){
    tm.removeRow(i);
          }
} 
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"error"+e.getMessage());
        }

placeorder_btn.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_transactionWindowActivated

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
npr_txt.setText("0");
 off_txt.setText("0");
 office_txt.setText("0");
 parts_txt.setText("0");
 mag_txt.setText("0");
 milk_txt.setText("0");
 mobiles_txt.setText("0");
 poly_txt.setText("0");
 sch_txt.setText("0");
 sofa_txt.setText("0");
 tables_txt.setText("0");
steel_txt.setText("0");
 utensils_txt.setText("0");
 alu_txt.setText("0");
 battery_txt.setText("0");
 beds_txt.setText("0");
 cds_txt.setText("0");
 glass_txt.setText("0");
 home_txt.setText("0");
 copper_txt.setText("0");
 iron_txt.setText("0");
 machinery_txt.setText("0");
 cupboards_txt.setText("0");
 
        tm =( DefaultTableModel)client_table.getModel();
int rows = tm.getRowCount();
if(rows>0){
    for(int i = 0 ; i <rows; i++){
        tm.removeRow(0);
    }
}



// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void placeorder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeorder_btnActionPerformed
String hh= ulbl.getText();
String f =total.getText();
 Random no = new Random();
int r= no.nextInt(1000000);
Object ssss= r;
String num= ssss.toString();
 JOptionPane.showMessageDialog(null,"Your receipt number is " +r+ " .You MUST note this number in order to get your stock and for payment transactions." );

        try{
stmt=con.createStatement();
String query="insert into transaction values ("+'\"'+hh+'\"'+","+num+","+f+","+-Integer.parseInt(npr_txt.getText())+","+-Integer.parseInt(sch_txt.getText())+","+-Integer.parseInt(off_txt.getText())+","+-Integer.parseInt(mag_txt.getText())+","+-Integer.parseInt(parts_txt.getText())+","+-Integer.parseInt(home_txt.getText())+","+-Integer.parseInt(mobiles_txt.getText())+","+-Integer.parseInt(machinery_txt.getText())+","+-Integer.parseInt(cds_txt.getText())+","+-Integer.parseInt(battery_txt.getText())+","+-Integer.parseInt(tables_txt.getText())+","+-Integer.parseInt(sofa_txt.getText())+","+-Integer.parseInt(cupboards_txt.getText())+","+-Integer.parseInt(beds_txt.getText())+","+-Integer.parseInt(glass_txt.getText())+","+-Integer.parseInt(poly_txt.getText())+","+-Integer.parseInt(milk_txt.getText())+","+-Integer.parseInt(utensils_txt.getText())+","+-Integer.parseInt(office_txt.getText())+","+-Integer.parseInt(alu_txt.getText())+","+-Integer.parseInt(iron_txt.getText())+","+-Integer.parseInt(copper_txt.getText())+","+-Integer.parseInt(steel_txt.getText())+");";
stmt.executeUpdate(query);

        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,"error"+e);
}

 npr_txt.setText("0");
 off_txt.setText("0");
 office_txt.setText("0");
 parts_txt.setText("0");
 mag_txt.setText("0");
 milk_txt.setText("0");
 mobiles_txt.setText("0");
 poly_txt.setText("0");
 sch_txt.setText("0");
 sofa_txt.setText("0");
 tables_txt.setText("0");
steel_txt.setText("0");
 utensils_txt.setText("0");
 alu_txt.setText("0");
 battery_txt.setText("0");
 beds_txt.setText("0");
 cds_txt.setText("0");
 glass_txt.setText("0");
 home_txt.setText("0");
 copper_txt.setText("0");
 iron_txt.setText("0");
 machinery_txt.setText("0");
 cupboards_txt.setText("0");


    // TODO add your handling code here:
}//GEN-LAST:event_placeorder_btnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
clbl.setText(client_login.ca);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void placeorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeorder1ActionPerformed
transaction.setVisible(true);
task.dispose();
task.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_placeorder1ActionPerformed

    private void mag_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mag_txtActionPerformed
        //(Integer.parseInt(total.getText())!=0)||total.getText().equals("") TODO add your handling code here:
    }//GEN-LAST:event_mag_txtActionPerformed

    private void calc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_btnActionPerformed
try{tm=(DefaultTableModel)client_table.getModel();
        if(tm.getRowCount()!=0||(Integer.parseInt(tm.getValueAt(0, 3).toString()))!=0){
        int j = tm.getRowCount();
double sum,y=0 ;
int i;
for (i=j-1;i>=0;--i){
     Object ss= tm.getValueAt(i,3);
     sum= Double.parseDouble(ss.toString());
     y= y+sum;

}
total.setText(" "+y);

placeorder_btn.setEnabled(true);
        }
        }
catch(Exception e){

}

// TODO add your handling code here:
}//GEN-LAST:event_calc_btnActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
homepage a = new homepage();
a.setVisible(true);
dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void currentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentActionPerformed

         tm =( DefaultTableModel)jTable1.getModel();
         try{
        stmt=con.createStatement();
        String query="select sum(npr),sum(sch),sum(off),sum(mag),sum(parts),sum(home),sum(mobile),sum(machinery),sum(cds),sum(battery),sum(tbl),sum(sofa),sum(cupboards),sum(beds),sum(glass),sum(poly),sum(milk),sum(utensils),sum(office),sum(alu),sum(iron),sum(copper),sum(steel) from transaction;";
rs=stmt.executeQuery(query);

      rs.first();
Object a[]={rs.getInt(1),rs.getInt(2),rs.getInt(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7),rs.getInt(8),rs.getInt(9),rs.getInt(10),rs.getInt(11),rs.getInt(12),rs.getInt(13),rs.getInt(14),rs.getInt(15),rs.getInt(16),rs.getInt(17),rs.getInt(18),rs.getInt(19),rs.getInt(20),rs.getInt(21),rs.getInt(22),rs.getInt(23)};
            tm.addRow(a);



    }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
cs.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_currentActionPerformed

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
if (evt.getStateChange()==1){

    furniture.setVisible(true);

}
else if (evt.getStateChange()==2){
  furniture.setVisible(false);

}

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void npr_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_npr_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(npr) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(npr_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    npr_txt.setText("0");
}

}
catch(Exception e){

npr_txt.setText("0");
}
    // TODO add your handling code here:
    }//GEN-LAST:event_npr_txtFocusLost

    private void mag_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mag_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(mag) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(mag_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    mag_txt.setText("0");

}

}
catch(Exception e){

mag_txt.setText("0");

}        // TODO add your handling code here:
    }//GEN-LAST:event_mag_txtFocusLost

    private void sch_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sch_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(sch) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(sch_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    sch_txt.setText("0");
}

}
catch(Exception e){

sch_txt.setText("0");
}        // TODO add your handling code here:
    }//GEN-LAST:event_sch_txtFocusLost

    private void off_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_off_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(off) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(off_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    off_txt.setText("0");
}

}
catch(Exception e){
 off_txt.setText("0");
}        // TODO add your handling code here:
    }//GEN-LAST:event_off_txtFocusLost

    private void cupboards_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cupboards_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(cupboards) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(cupboards_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    cupboards_txt.setText("0");
}

}
catch(Exception e){
 cupboards_txt.setText("0");
}        // TODO add your handling code here:
    }//GEN-LAST:event_cupboards_txtFocusLost

    private void beds_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_beds_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(beds) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(beds_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
   beds_txt.setText("0");
}

}
catch(Exception e){
   beds_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_beds_txtFocusLost

    private void glass_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_glass_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(glass) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(glass_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    glass_txt.setText("0");
}

}
catch(Exception e){
glass_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_glass_txtFocusLost

    private void sofa_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sofa_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(sofa) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(sofa_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    sofa_txt.setText("0");
}

}
catch(Exception e){
 sofa_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_sofa_txtFocusLost

    private void tables_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tables_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(tble) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(tables_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    tables_txt.setText("0");
}

}
catch(Exception e){
 tables_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_tables_txtFocusLost

    private void copper_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_copper_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(copper) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(copper_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    copper_txt.setText("0");
}

}
catch(Exception e){
copper_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_copper_txtFocusLost

    private void iron_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iron_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(iron) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(iron_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    iron_txt.setText("0");
}

}
catch(Exception e){
iron_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_iron_txtFocusLost

    private void alu_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alu_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(alu) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(alu_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    alu_txt.setText("0");
}

}
catch(Exception e){
 alu_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_alu_txtFocusLost

    private void steel_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_steel_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(steel) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(steel_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    steel_txt.setText("0");
}

}
catch(Exception e){
  steel_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_steel_txtFocusLost

    private void home_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_home_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(home) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(home_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    home_txt.setText("0");
}

}
catch(Exception e){
home_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_home_txtFocusLost

    private void battery_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_battery_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(battery) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(battery_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    battery_txt.setText("0");
}

}
catch(Exception e){
 battery_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_battery_txtFocusLost

    private void machinery_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_machinery_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(machinery) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(machinery_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    machinery_txt.setText("0");
}

}
catch(Exception e){
machinery_txt.setText("0");
}         // TODO add your handling code here:
    }//GEN-LAST:event_machinery_txtFocusLost

    private void cds_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cds_txtFocusLost
  try {
stmt=con.createStatement();
String query ="select sum(cds) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(cds_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    cds_txt.setText("0");
}

}
catch(Exception e){
 cds_txt.setText("0");
}                    // TODO add your handling code here:
    }//GEN-LAST:event_cds_txtFocusLost

    private void parts_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parts_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(parts) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(parts_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    parts_txt.setText("0");
}

}
catch(Exception e){
 parts_txt.setText("0");
}                // TODO add your handling code here:
    }//GEN-LAST:event_parts_txtFocusLost

    private void mobiles_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobiles_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(mobiles) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(mobiles_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    mobiles_txt.setText("0");
}

}
catch(Exception e){
mobiles_txt.setText("0");
}                // TODO add your handling code here:
    }//GEN-LAST:event_mobiles_txtFocusLost

    private void utensils_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_utensils_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(utensils) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(utensils_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    utensils_txt.setText("0");
}

}
catch(Exception e){
  utensils_txt.setText("0");
}                // TODO add your handling code here:
    }//GEN-LAST:event_utensils_txtFocusLost

    private void office_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_office_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(home) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(home_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    home_txt.setText("0");
}

}
catch(Exception e){
home_txt.setText("0");
}                // TODO add your handling code here:
    }//GEN-LAST:event_office_txtFocusLost

    private void milk_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_milk_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(milk) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(milk_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    milk_txt.setText("0");
}

}
catch(Exception e){
 milk_txt.setText("0");
}                // TODO add your handling code here:
    }//GEN-LAST:event_milk_txtFocusLost

    private void poly_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_poly_txtFocusLost
try {
stmt=con.createStatement();
String query ="select sum(poly) from transaction;";
rs= stmt.executeQuery(query);
rs.first();
int stk=rs.getInt(1);
int num= Integer.parseInt(poly_txt.getText());
if(num>stk){
    JOptionPane.showMessageDialog(null,"sorry not enough stocks ");
    poly_txt.setText("0");
}

}
catch(Exception e){
poly_txt.setText("0");
}                // TODO add your handling code here:
    }//GEN-LAST:event_poly_txtFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
npr_txt.setText("0");
 off_txt.setText("0");
 office_txt.setText("0");
 parts_txt.setText("0");
 mag_txt.setText("0");
 milk_txt.setText("0");
 mobiles_txt.setText("0");
 poly_txt.setText("0");
 sch_txt.setText("0");
 sofa_txt.setText("0");
 tables_txt.setText("0");
steel_txt.setText("0");
 utensils_txt.setText("0");
 alu_txt.setText("0");
 battery_txt.setText("0");
 beds_txt.setText("0");
 cds_txt.setText("0");
 glass_txt.setText("0");
 home_txt.setText("0");
 copper_txt.setText("0");
 iron_txt.setText("0");
 machinery_txt.setText("0");
 cupboards_txt.setText("0");
 
        tm =( DefaultTableModel)client_table.getModel();
int rows = tm.getRowCount();
if(rows>0){
    for(int i = 0 ; i <rows; i++){
        tm.removeRow(0);
    }
}


total.setText("");
calc_btn.setEnabled(false);
placeorder_btn.setEnabled(false);

homepage home =new homepage();
home.setVisible(true);
transaction.setVisible(false);
dispose();
                                               // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client_workspace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alu_txt;
    private javax.swing.JLabel alulbl;
    private javax.swing.JLabel back;
    private javax.swing.JTextField battery_txt;
    private javax.swing.JLabel batterylbl;
    private javax.swing.JTextField beds_txt;
    private javax.swing.JLabel bedslbl;
    private javax.swing.JButton calc_btn;
    private javax.swing.JTextField cds_txt;
    private javax.swing.JLabel cdslbl;
    private javax.swing.JLabel clbl;
    private javax.swing.JButton clear;
    private javax.swing.JTable client_table;
    private javax.swing.JTextField copper_txt;
    private javax.swing.JLabel copperlbl;
    private javax.swing.JLabel cs;
    private javax.swing.JTextField cupboards_txt;
    private javax.swing.JLabel cupboardslbl;
    private javax.swing.JButton current;
    private javax.swing.JLabel currentstocks;
    private javax.swing.JPanel eWaste;
    private javax.swing.JPanel furniture;
    private javax.swing.JTextField glass_txt;
    private javax.swing.JLabel glasslbl;
    private javax.swing.JTextField home_txt;
    private javax.swing.JLabel homelbl;
    private javax.swing.JTextField iron_txt;
    private javax.swing.JLabel ironlbl;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField machinery_txt;
    private javax.swing.JLabel machinerylbl;
    private javax.swing.JTextField mag_txt;
    private javax.swing.JLabel maglbl;
    private javax.swing.JPanel metals;
    private javax.swing.JTextField milk_txt;
    private javax.swing.JLabel milklbl;
    private javax.swing.JTextField mobiles_txt;
    private javax.swing.JLabel mobileslbl;
    private javax.swing.JTextField npr_txt;
    private javax.swing.JLabel nprlbl;
    private javax.swing.JTextField off_txt;
    private javax.swing.JTextField office_txt;
    private javax.swing.JLabel officelbl;
    private javax.swing.JLabel offlbl;
    private javax.swing.JPanel paper;
    private javax.swing.JTextField parts_txt;
    private javax.swing.JLabel partslbl;
    private javax.swing.JButton place;
    private javax.swing.JButton placeorder1;
    private javax.swing.JButton placeorder_btn;
    private javax.swing.JPanel plastics;
    private javax.swing.JTextField poly_txt;
    private javax.swing.JLabel polylbl;
    private javax.swing.JTextField sch_txt;
    private javax.swing.JLabel schlbl;
    private javax.swing.JTextField sofa_txt;
    private javax.swing.JLabel sofalbl;
    private javax.swing.JTextField steel_txt;
    private javax.swing.JLabel steellbl;
    private javax.swing.JTextField tables_txt;
    private javax.swing.JLabel tableslbl;
    private javax.swing.JFrame task;
    private javax.swing.JLabel total;
    private javax.swing.JFrame transaction;
    private javax.swing.JLabel ulbl;
    private javax.swing.JTextField utensils_txt;
    private javax.swing.JLabel utensilslbl;
    // End of variables declaration//GEN-END:variables

}
