import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * client_login.java
 *
 * Created on Nov 15, 2002, 10:50:01 AM
 */

/**
 *
 * @author students
 */
public class client_login extends javax.swing.JFrame {
static String ca;
    Statement stmt = null;
ResultSet rs = null;
Connection con = null;
static int count = 0;



int r;
int j1,i;
Timer t=new Timer(100,new ActionListener(){
public void actionPerformed(ActionEvent e){

    int r=p1.getValue();
p1.setValue(r+1);
  ++i;
 if(i%10==0){

   lbl.setVisible(true);
 }
 else {
     lbl.setVisible(false);
 }



    
 } } );

    /** Creates new form client_login */
    public client_login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        p1 = new javax.swing.JProgressBar();
        jdlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        login_ID = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jDialog1.setBounds(new java.awt.Rectangle(400, 0, 0, 0));
        jDialog1.setMinimumSize(new java.awt.Dimension(560, 120));
        jDialog1.setModal(true);
        jDialog1.setUndecorated(true);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialog1WindowActivated(evt);
            }
        });
        jDialog1.getContentPane().setLayout(null);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("%");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jDialog1.getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 80, 20, 20);

        p1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p1StateChanged(evt);
            }
        });
        jDialog1.getContentPane().add(p1);
        p1.setBounds(100, 90, 370, 10);

        jdlbl.setForeground(new java.awt.Color(255, 255, 255));
        jDialog1.getContentPane().add(jdlbl);
        jdlbl.setBounds(40, 80, 20, 30);

        jLabel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel3FocusGained(evt);
            }
        });
        jDialog1.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 70, 40);

        lbl.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("LOADING...");
        jDialog1.getContentPane().add(lbl);
        lbl.setBounds(90, 20, 240, 35);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading.JPG"))); // NOI18N
        jDialog1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 574, 122);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Login");
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));
        setMinimumSize(new java.awt.Dimension(450, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(pass2);
        pass2.setBounds(150, 100, 118, 20);
        getContentPane().add(login_ID);
        login_ID.setBounds(151, 57, 118, 20);

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(14, 150, 100, 23);

        jLabel1.setText("User ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 60, 90, 14);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 100, 14);

        signup.setText("sign up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(149, 150, 110, 23);

        jLabel5.setBackground(new java.awt.Color(51, 51, 255));
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Return to Home");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(267, 190, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
try{
    boolean ans=false;
 String aa = login_ID.getText();
 String  str=new String(pass2.getPassword());
 String ss= "select * from client_record;";
 stmt=con.createStatement();
rs = stmt.executeQuery(ss);
System.out.print("reached before loop");
 while (rs.next()){
     String id=rs.getString(5);
     String password = rs.getString(6);
     if ((aa.equals(id))&&(str.equals(password))){
         ans=true;
         break;
     }

 }
if(ans ==true){
    jDialog1.setVisible(true);
}
else
    JOptionPane.showMessageDialog(null,"please check your password and userid");
 

}
catch(Exception e){
JOptionPane.showMessageDialog(null,"error in finding "+e.getMessage());
}
 

    ca=login_ID.getText(); 

Login_Form w = new Login_Form();
w.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void jDialog1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowActivated
        t.start();        // TODO add your handling code here:
}//GEN-LAST:event_jDialog1WindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
try {
    Class.forName("java.sql.Driver");
     con = DriverManager.getConnection("jdbc:mysql://localHost/ip_project12","root","");
    System.out.println("connectivity done");
            }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "Connection Not Done");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
client_registeration p = new client_registeration();
p.setVisible(true);
client_login r = new client_login();
r.setVisible(false);
r.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
try{new homepage().setVisible(true);
        }
catch(Exception e){
new homepage().setVisible(true);
      
}
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void p1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p1StateChanged
   client_login p = new client_login();
        if(p1.getValue()==100){
            t.stop();
            this.dispose();
            p.setVisible(false);}
        if (p1.getValue()==100){
            client_workspace a= new client_workspace();
            a.setVisible(true);
            jDialog1.setVisible(false);
            dispose();

        }
        jdlbl.setText(""+p1.getValue());

        // TODO add your handling code here:
}//GEN-LAST:event_p1StateChanged

    private void jLabel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel3FocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_jLabel3FocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              client_login g=  new client_login();
                       g.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jdlbl;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField login_ID;
    private javax.swing.JProgressBar p1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JButton signup;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
