
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * clothes.java
 *
 * Created on Sep 4, 2010, 10:24:15 AM
 */

/**
 *
 * @author Administrator
 */
public class clothes extends javax.swing.JFrame {

    /** Creates new form clothes */
    public clothes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HELPAGE = new javax.swing.JCheckBox();
        SALMAN = new javax.swing.JCheckBox();
        GIVE = new javax.swing.JCheckBox();
        CRY = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        mainmenu_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Donate Clothes");
        setMinimumSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("<html>The clothes you want to donate can be given to the NGO's directly .<br> The representatives will come to your homes and collect your donations<html>  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 530, 100);

        HELPAGE.setText("HELPAGE INDIA");
        HELPAGE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HELPAGEMouseMoved(evt);
            }
        });
        getContentPane().add(HELPAGE);
        HELPAGE.setBounds(30, 180, 120, 23);

        SALMAN.setText("BEING HUMAN");
        SALMAN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SALMANMouseMoved(evt);
            }
        });
        SALMAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALMANActionPerformed(evt);
            }
        });
        getContentPane().add(SALMAN);
        SALMAN.setBounds(460, 180, 120, 23);

        GIVE.setText("GIVE INDIA ");
        GIVE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GIVEMouseMoved(evt);
            }
        });
        getContentPane().add(GIVE);
        GIVE.setBounds(30, 240, 110, 23);

        CRY.setText("CRY");
        CRY.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CRYMouseMoved(evt);
            }
        });
        getContentPane().add(CRY);
        CRY.setBounds(460, 220, 107, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 160, 290, 119);

        jButton1.setText("call them home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 300, 150, 23);

        mainmenu_btn.setText("Main Menu");
        mainmenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_btnActionPerformed(evt);
            }
        });
        getContentPane().add(mainmenu_btn);
        mainmenu_btn.setBounds(150, 300, 130, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading.JPG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 560, 130);

        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Return to Home");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 370, 190, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainmenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_btnActionPerformed
main_form oo =new main_form();
oo.setVisible(true);
this.dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_mainmenu_btnActionPerformed

    private void SALMANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALMANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SALMANActionPerformed

    private void HELPAGEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HELPAGEMouseMoved
     jPanel1.setVisible(true);
        jTextArea1.setText(HELPAGE.getText()+'\n'+": Donate clothes to HELPAGE INDIA."+'\n'+"For further details visit our site In$pirex.Corp.in");    // TODO add your handling code here:
    }//GEN-LAST:event_HELPAGEMouseMoved

    private void GIVEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GIVEMouseMoved
        jPanel1.setVisible(true);
        jTextArea1.setText(GIVE.getText()+'\n'+": Donate clothes to GIVE INDIA."+'\n'+"For further details visit our site In$pirex.Corp.in"); // TODO add your handling code here:
    }//GEN-LAST:event_GIVEMouseMoved

    private void SALMANMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALMANMouseMoved
       jPanel1.setVisible(true);
        jTextArea1.setText(SALMAN.getText()+'\n'+": Donate clothes to BEING HUMAN."+'\n'+"For further details visit our site In$pirex.Corp.in");  // TODO add your handling code here:
    }//GEN-LAST:event_SALMANMouseMoved

    private void CRYMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRYMouseMoved
 jPanel1.setVisible(true);
        jTextArea1.setText(CRY.getText()+'\n'+": Donate clothes to CRY."+'\n'+"For further details visit our site In$pirex.Corp.in");        // TODO add your handling code here:
    }//GEN-LAST:event_CRYMouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(HELPAGE.isSelected()||SALMAN.isSelected()||CRY.isSelected()||GIVE.isSelected()){

            JOptionPane.showMessageDialog(null,"You will be soon contacted by the desired NGO's");

        } else{
            JOptionPane.showMessageDialog(null,"Please select a desired NGO.");


        }


        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
homepage p =new homepage();
p.setVisible(true);
dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clothes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CRY;
    private javax.swing.JCheckBox GIVE;
    private javax.swing.JCheckBox HELPAGE;
    private javax.swing.JCheckBox SALMAN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mainmenu_btn;
    // End of variables declaration//GEN-END:variables

}
