import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Random;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * workspace.java
 *
 * Created on Sep 4, 2010, 10:32:37 AM
 */

/**
 *
 * @author Administrator
 */

public class workspace extends javax.swing.JFrame {

    public DefaultTableModel tm =null;
Connection con=null;
Statement stmt = null;
ResultSet rs=null;
paper  bb = new paper();
eWaste  cc = new eWaste();
furniture  dd = new furniture();
plastic ee = new plastic();
metal ff = new metal();
double y;



    /** Creates new form workspace */
    public workspace() {
        initComponents();



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        work_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        calc_btn = new javax.swing.JButton();
        placeorder_btn = new javax.swing.JButton();
        mainmenu_btn = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        ulbl = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Workspace");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        work_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ITEMS", "QUANTITY", "PROJECTED AMOUNT"
            }
        ));
        work_table.setCellSelectionEnabled(true);
        work_table.setEnabled(false);
        work_table.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(work_table);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WORKSPACE");

        calc_btn.setText("CALCULATE");
        calc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_btnActionPerformed(evt);
            }
        });

        placeorder_btn.setText("PLACE ORDER");
        placeorder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeorder_btnActionPerformed(evt);
            }
        });

        mainmenu_btn.setText("MAIN MENU");
        mainmenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu_btnActionPerformed(evt);
            }
        });

        total.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Total")));

        ulbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ulbl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ulblFocusLost(evt);
            }
        });

        clear_btn.setText("CLEAR");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("LOGOUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/REcyclone2.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(calc_btn)
                                    .addGap(29, 29, 29)
                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(mainmenu_btn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(placeorder_btn)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calc_btn)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mainmenu_btn)
                            .addComponent(clear_btn)))
                    .addComponent(placeorder_btn))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
ulbl.setText(Login_Form.a);

tm =( DefaultTableModel)work_table.getModel();
if(tm.getValueAt(0,0)==null){

Object[] m = {bb.nprlbl1,bb.nprcbx,bb.nprlbl2};
tm.addRow(m);
Object[] n = {bb.schlbl1,bb.schcbx,bb.schlbl2};
tm.addRow(n);
Object[] o = {bb.offlbl1,bb.offcbx,bb.offlbl2};
tm.addRow(o);
Object[] p = {bb.maglbl1,bb.magcbx,bb.maglbl2};
tm.addRow(p);


Object[] q = {cc.partslbl1,cc.partscbx,cc.partslbl2};
tm.addRow(q);
Object[] r = {cc.homelbl1,cc.homecbx,cc.homelbl2};
tm.addRow(r);
Object[] s = {cc.mobilelbl1,cc.mobilecbx,cc.mobilelbl2};
tm.addRow(s);
Object[] t = {cc.machinerylbl1,cc.machinerycbx,cc.machinerylbl2};
tm.addRow(t);
Object[] u = {cc.cdslbl1,cc.cdscbx,cc.cdslbl2};
tm.addRow(u);
Object[] v = {cc.batterylbl1,cc.batterycbx,cc.batterylbl2};
tm.addRow(v);


Object[] w = {dd.tablelbl1,dd.tablecbx,dd.tablelbl2};
tm.addRow(w);
Object[] x = {dd.sofalbl1,dd.sofacbx,dd.sofalbl2};
tm.addRow(x);
Object[] y = {dd.cupboardslbl1,dd.cupboardscbx,dd.cupboardslbl2};
tm.addRow(y);
Object[] z = {dd.bedslbl1,dd.bedscbx,dd.bedslbl2};
tm.addRow(z);
Object[] a = {dd.glasslbl1,dd.glasscbx,dd.glasslbl2};
tm.addRow(a);


Object[] b = {ee.polylbl1,ee.polycbx,ee.polylbl2};
tm.addRow(b);
Object[] c = {ee.milklbl1,ee.milkcbx,ee.milklbl2};
tm.addRow(c);
Object[] d = {ee.utensilslbl1,ee.utensilscbx,ee.utensilslbl2};
tm.addRow(d);
Object[] e = {ee.officelbl1,ee.officecbx,ee.officelbl2};
tm.addRow(e);


Object[] f = {ff.alulbl1,ff.alucbx,ff.alulbl2};
tm.addRow(f);
Object[] g = {ff.ironlbl1,ff.ironcbx,ff.ironlbl2};
tm.addRow(g);
Object[] h= {ff.copperlbl1,ff.coppercbx,ff.copperlbl2};
tm.addRow(h);
Object[] k = {ff.steellbl1,ff.steelcbx,ff.steellbl2};
tm.addRow(k);

int j=tm.getRowCount();
int i;
for(i=j-2;i>=0;--i){
if (tm.getValueAt(i,0)==null){
    tm.removeRow(i);
}
}
}
placeorder_btn.setEnabled(false);
if(tm.getValueAt(0,0)==null&&tm.getValueAt(0,1)==null){
    calc_btn.setEnabled(false);
}


// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void mainmenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu_btnActionPerformed
main_form sun = new main_form();
sun.setVisible(true);
dispose();

        // TODO add your handling code here:
}//GEN-LAST:event_mainmenu_btnActionPerformed

    private void calc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_btnActionPerformed
int j = tm.getRowCount();
double sum=0 ;
int i;
y=0;
for (i=j-2;i>=0;--i){
     Object ss= tm.getValueAt(i,2);
     sum= Double.parseDouble(ss.toString());
     y= y+sum;
     
}
total.setText(" "+y);
placeorder_btn.setEnabled(true);

}//GEN-LAST:event_calc_btnActionPerformed

    private void placeorder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeorder_btnActionPerformed

        Random no = new Random();
int r= no.nextInt(1000000);
Object ssss= r;
String num= ssss.toString();


String hh= ulbl.getText();
//String f =total.getText();
//int tot = -Integer.parseInt(f);
try{
    Class.forName("java.sql.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localHost/ip_project12","root","");
     stmt=con.createStatement();
     String query= "insert into transaction values ("+'\"'+hh+'\"'+","+num+","+-y+","+bb.nprcbx+","+bb.schcbx+","+bb.offcbx+","+bb.magcbx+","+cc.partscbx+","+cc.batterycbx+","+cc.cdscbx+","+cc.machinerycbx+","+cc.homecbx+","+cc.mobilecbx+","+dd.tablecbx+","+dd.sofacbx+","+dd.cupboardscbx+","+dd.bedscbx+","+dd.glasscbx+","+ee.officecbx+","+ee.milkcbx+","+ee.polycbx+","+ee.utensilscbx+","+ff.alucbx+","+ff.ironcbx+","+ff.coppercbx+","+ff.steelcbx+");";
    stmt.executeUpdate(query);
    con.close();
    stmt.close();
  JOptionPane.showMessageDialog(null,"Your receipt number is " +r+ " .You MUST note this number in order to get your payment in your account at the time of collection of your order!!!" );
}
catch(Exception o){
    JOptionPane.showMessageDialog(null,o);
}



        // TODO add your handling code here:
}//GEN-LAST:event_placeorder_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed

        tm =( DefaultTableModel)work_table.getModel();
int rows = tm.getRowCount();
if(rows>0){
    for(int i = 0 ; i <rows; i++){
        tm.removeRow(0);
    }
}
paper.nprlbl1=null;
paper.nprlbl2=null;
paper.nprcbx=null;
paper.schlbl1=null;
paper.schlbl2=null;
paper.schcbx=null;
paper.maglbl1=null;
paper.maglbl2=null;
paper.magcbx=null;
paper.offlbl1=null;
paper.offlbl2=null;
paper.offcbx=null;

eWaste.partslbl1=null;
eWaste.partslbl2=null;
eWaste.partscbx=null;
eWaste.homelbl1=null;
eWaste.homelbl2=null;
eWaste.homecbx=null;
eWaste.mobilelbl1=null;
eWaste.mobilelbl2=null;
eWaste.mobilecbx=null;
eWaste.cdslbl1=null;
eWaste.cdslbl2=null;
eWaste.cdscbx=null;
eWaste.machinerylbl1=null;
eWaste.machinerylbl2=null;
eWaste.machinerycbx=null;
eWaste.batterylbl1=null;
eWaste.batterylbl2=null;
eWaste.batterycbx=null;

 furniture.tablelbl1=null;
 furniture.tablelbl2=null;
 furniture.tablecbx=null;
 furniture.sofalbl1=null;
 furniture.sofalbl2=null;
 furniture.sofacbx=null;
 furniture.cupboardslbl1=null;
 furniture.cupboardslbl2=null;
 furniture.cupboardscbx=null;
 furniture.bedslbl1=null;
 furniture.bedslbl2=null;
 furniture.bedscbx=null;
 furniture.glasslbl1=null;
 furniture.glasslbl2=null;
 furniture.glasscbx=null;

metal.alulbl1=null;
metal.alulbl2=null;
metal.alucbx=null;
metal.ironlbl1=null;
metal.ironlbl2=null;
metal.ironcbx=null;
metal.copperlbl1=null;
metal.copperlbl2=null;
metal.coppercbx=null;
metal.steellbl1=null;
metal.steellbl2=null;
metal.steelcbx=null;

plastic.polylbl1=null;
plastic.polylbl2=null;
plastic.polycbx=null;
plastic.milklbl1=null;
plastic.milklbl2=null;
plastic.milkcbx=null;
plastic.utensilslbl1=null;
plastic.utensilslbl2=null;
plastic.utensilscbx=null;
plastic.officelbl1=null;
plastic.officelbl2=null;
plastic.officecbx=null;

total.setText("");
calc_btn.setEnabled(false);
placeorder_btn.setEnabled(false);
}//GEN-LAST:event_clear_btnActionPerformed

    private void ulblFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulblFocusLost
//String t= name_tf.getText();
//ulbl.setText(t);


        // TODO add your handling code here:
    }//GEN-LAST:event_ulblFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        tm =( DefaultTableModel)work_table.getModel();
int rows = tm.getRowCount();
if(rows>0){
    for(int i = 0 ; i <rows; i++){
        tm.removeRow(0);
    }
}
paper.nprlbl1=null;
paper.nprlbl2=null;
paper.nprcbx=null;
paper.schlbl1=null;
paper.schlbl2=null;
paper.schcbx=null;
paper.maglbl1=null;
paper.maglbl2=null;
paper.magcbx=null;
paper.offlbl1=null;
paper.offlbl2=null;
paper.offcbx=null;

eWaste.partslbl1=null;
eWaste.partslbl2=null;
eWaste.partscbx=null;
eWaste.homelbl1=null;
eWaste.homelbl2=null;
eWaste.homecbx=null;
eWaste.mobilelbl1=null;
eWaste.mobilelbl2=null;
eWaste.mobilecbx=null;
eWaste.cdslbl1=null;
eWaste.cdslbl2=null;
eWaste.cdscbx=null;
eWaste.machinerylbl1=null;
eWaste.machinerylbl2=null;
eWaste.machinerycbx=null;
eWaste.batterylbl1=null;
eWaste.batterylbl2=null;
eWaste.batterycbx=null;

 furniture.tablelbl1=null;
 furniture.tablelbl2=null;
 furniture.tablecbx=null;
 furniture.sofalbl1=null;
 furniture.sofalbl2=null;
 furniture.sofacbx=null;
 furniture.cupboardslbl1=null;
 furniture.cupboardslbl2=null;
 furniture.cupboardscbx=null;
 furniture.bedslbl1=null;
 furniture.bedslbl2=null;
 furniture.bedscbx=null;
 furniture.glasslbl1=null;
 furniture.glasslbl2=null;
 furniture.glasscbx=null;

metal.alulbl1=null;
metal.alulbl2=null;
metal.alucbx=null;
metal.ironlbl1=null;
metal.ironlbl2=null;
metal.ironcbx=null;
metal.copperlbl1=null;
metal.copperlbl2=null;
metal.coppercbx=null;
metal.steellbl1=null;
metal.steellbl2=null;
metal.steelcbx=null;

plastic.polylbl1=null;
plastic.polylbl2=null;
plastic.polycbx=null;
plastic.milklbl1=null;
plastic.milklbl2=null;
plastic.milkcbx=null;
plastic.utensilslbl1=null;
plastic.utensilslbl2=null;
plastic.utensilscbx=null;
plastic.officelbl1=null;
plastic.officelbl2=null;
plastic.officecbx=null;

total.setText("");
calc_btn.setEnabled(false);
placeorder_btn.setEnabled(false);




homepage w = new homepage();
w.setVisible(true);
dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               workspace bnm = new workspace();
                       bnm.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainmenu_btn;
    private javax.swing.JButton placeorder_btn;
    private javax.swing.JLabel total;
    private javax.swing.JLabel ulbl;
    private javax.swing.JTable work_table;
    // End of variables declaration//GEN-END:variables

}
