create table transaction(
name varchar(30),
receiptno int(11),
amount int(11),
npr integer,
sch integer,
off integer,
mag integer,
parts integer,
battery integer,
cds integer,
machinery integer,
home integer,
mobile integer,
tbl integer,
sofa integer,
cupboards integer,
beds integer,
glass integer,
office integer,
milk integer,
poly integer,
utensils integer,
alu integer,
iron integer,
copper integer,
steel integer     );

