
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class points extends javax.swing.JFrame {

    Connection con=null;
Statement stmt=null;
ResultSet rs=null;
DefaultTableModel tm =null;

    /**
     * Creates new form points
     */
    public points() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        current = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalpts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "id", "name", "points"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 70, 436, 360);

        jLabel1.setText("Current Points");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 100, 14);

        current.setText("0");
        getContentPane().add(current);
        current.setBounds(240, 34, 90, 20);

        jButton1.setText("Add Player/ Points to Table");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 460, 210, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 460, 100, 23);

        jLabel2.setText("Total Points");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 40, 70, 20);

        totalpts.setText("0");
        getContentPane().add(totalpts);
        totalpts.setBounds(450, 40, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

try
{
       current.setText(points_calculation.globaltotal+"");     
        tm=(DefaultTableModel)jTable1.getModel();
       
       
       Class.forName("java.sql.Driver");

       con=DriverManager.getConnection("jdbc:mysql://localHost/cfl","root","1234");
        System.out.println("connection established");

       stmt=con.createStatement();
 
       int id,points;
       String player;
       
       id=playerlist.globalid;
       player=playerlist.globalplayer;
       points=points_calculation.globaltotal;
       
       Rankings r = new Rankings();
       
       String q1="select * from points where owner_name='"+r.globaluser+"';";

       ResultSet rs=stmt.executeQuery(q1);
       while(rs.next())
       {    
       Object a[]={rs.getInt(1),rs.getString(2),rs.getInt(3)};
       tm.addRow(a);
       }
       
       String q2="select sum(points) from points where owner_name='"+r.globaluser+"';";
       ResultSet tt=stmt.executeQuery(q2);        
       
       tt.first();
       int total=tt.getInt(1);
       totalpts.setText(total+"");
       
       
}
catch(Exception e)
{
         JOptionPane.showMessageDialog(null, "First select a player!!");
       
}
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
       current.setText(points_calculation.globaltotal+"");     
        tm=(DefaultTableModel)jTable1.getModel();
       
       
       Class.forName("java.sql.Driver");

       con=DriverManager.getConnection("jdbc:mysql://localHost/cfl","root","1234");
        System.out.println("connection established");

       int id,points;
       String player;
       
       id=playerlist.globalid;
       player=playerlist.globalplayer;
       points=points_calculation.globaltotal;
       
int flag=0;

       stmt=con.createStatement();

       String q1= "select * from points where name='"+player+"';";
       ResultSet rs= stmt.executeQuery(q1);
       
       if(rs.next()==false)
       {
           flag=1;
       }
       else flag=0;
       
       System.out.println(flag);
       
 /*
       int rows=tm.getRowCount();
       for(int i=0; i<rows-1;i++)
       tm.removeRow(i);
 *//////////////////////
       
       Rankings r = new Rankings();
       
       if (flag==1)
     { 
       String q2= "insert into points values("+id+","+'\"'+player+'\"'+","+points+","+'\"'+r.globaluser+'\"'+");";
      stmt.executeUpdate(q2);

       int rows=tm.getRowCount();
       for(int i=rows-1;i>=0;i--)
       tm.removeRow(i);
       
      
      JOptionPane.showMessageDialog(null, "Player Inserted!!");
     }
       else       
       if(flag==0)
       {
       String q2= "update points set points=points+"+points+" where name='"+player+"';";
      stmt.executeUpdate(q2);

       int rows=tm.getRowCount();
       for(int i=rows-1;i>=0;i--)
       tm.removeRow(i);

     JOptionPane.showMessageDialog(null, "Player Points Updated!!");
      }
       
}
catch(Exception e)
{
         JOptionPane.showMessageDialog(null, e);
       
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{

        Class.forName("java.sql.Driver");

        con=DriverManager.getConnection("jdbc:mysql://localHost/cfl","root","1234");
        System.out.println("connection established");
       
       stmt=con.createStatement();

       String q1= "update rankings set total="+Integer.parseInt(totalpts.getText())+" where owner= '"+Rankings.globaluser+"' ;";
       stmt.executeUpdate(q1);
       
       
       
       
       
}
catch(Exception e)
{
         JOptionPane.showMessageDialog(null, e);
       
}

        
        
        /////////////////////////////////////////////////////////////////
      
        this.dispose();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

        
        jButton1.setEnabled(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new points().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel current;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalpts;
    // End of variables declaration//GEN-END:variables
}
