/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
public class points_calculation extends javax.swing.JFrame {
static int globaltotal;
    /**
     * Creates new form points_calculation
     */
    public points_calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        runs = new javax.swing.JTextField();
        balls = new javax.swing.JTextField();
        fours = new javax.swing.JTextField();
        sixes = new javax.swing.JTextField();
        overs = new javax.swing.JTextField();
        wickets = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        catches = new javax.swing.JTextField();
        runouts = new javax.swing.JTextField();
        stumpings = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        maidens = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        strikerate = new javax.swing.JLabel();
        economyrate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        given = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("RUNS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 100, 40, 20);

        jLabel2.setText("BALLS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 130, 40, 20);

        jLabel3.setText("FOURS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 160, 50, 20);

        jLabel4.setText("SIXES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 190, 40, 20);

        jLabel5.setText("OVERS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 100, 50, 20);

        jLabel6.setText("WICKETS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 130, 60, 20);

        runs.setText("0");
        runs.setName("runs"); // NOI18N
        getContentPane().add(runs);
        runs.setBounds(150, 100, 60, 20);

        balls.setText("0");
        balls.setName("balls"); // NOI18N
        balls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballsActionPerformed(evt);
            }
        });
        getContentPane().add(balls);
        balls.setBounds(150, 130, 60, 20);

        fours.setText("0");
        fours.setName("fours"); // NOI18N
        fours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursActionPerformed(evt);
            }
        });
        getContentPane().add(fours);
        fours.setBounds(150, 160, 60, 20);

        sixes.setText("0");
        sixes.setName("sixes"); // NOI18N
        getContentPane().add(sixes);
        sixes.setBounds(150, 190, 60, 20);

        overs.setText("0");
        overs.setName("overs"); // NOI18N
        overs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oversActionPerformed(evt);
            }
        });
        getContentPane().add(overs);
        overs.setBounds(320, 100, 60, 20);

        wickets.setText("0");
        wickets.setName("wickets"); // NOI18N
        getContentPane().add(wickets);
        wickets.setBounds(320, 130, 60, 20);

        jLabel7.setText("CATCHES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 260, 70, 20);

        jLabel8.setText("RUNOUTS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 290, 70, 20);

        jLabel9.setText("STUMPINGS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 320, 70, 20);

        catches.setText("0");
        catches.setName("catches"); // NOI18N
        getContentPane().add(catches);
        catches.setBounds(290, 260, 60, 20);

        runouts.setText("0");
        runouts.setName("runouts"); // NOI18N
        runouts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runoutsActionPerformed(evt);
            }
        });
        getContentPane().add(runouts);
        runouts.setBounds(290, 290, 60, 20);

        stumpings.setText("0");
        stumpings.setName("stumpings"); // NOI18N
        getContentPane().add(stumpings);
        stumpings.setBounds(290, 320, 60, 20);

        jLabel10.setText("TOTAL");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 370, 50, 20);

        total.setText("0");
        getContentPane().add(total);
        total.setBounds(490, 370, 60, 14);

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 370, 150, 23);

        jLabel12.setText("MAIDENS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 160, 60, 20);

        maidens.setText("0");
        maidens.setName("maidens"); // NOI18N
        getContentPane().add(maidens);
        maidens.setBounds(320, 160, 60, 20);

        jLabel13.setText(" STRIKE RATE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 100, 90, 20);

        jLabel14.setText("ECONOMY RATE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 140, 100, 20);

        strikerate.setText("0");
        strikerate.setName("strikerate"); // NOI18N
        getContentPane().add(strikerate);
        strikerate.setBounds(550, 100, 50, 14);

        economyrate.setText("0");
        economyrate.setName("economyrate"); // NOI18N
        getContentPane().add(economyrate);
        economyrate.setBounds(550, 140, 50, 14);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel17.setText("POINTS CALCULATION");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(130, 10, 430, 50);

        jLabel11.setText("RUNS (GIVEN)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 194, 100, 30);

        given.setText("0");
        getContentPane().add(given);
        given.setBounds(360, 200, 50, 20);

        jButton2.setText("View Points ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 370, 160, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        try
        {
        int run=0, ball=0,four=0,six=0,wicket=0,over=0,catche=0,maiden=0,give=0,runout=0,stumping=0;
        
        int sum=0;
        
        int strike=0;
        int economy=0;
        
        int runbonus=0;
        int wicketbonus=0;
        int strikebonus=0;
        
        run = Integer.parseInt(runs.getText());
        ball = Integer.parseInt(balls.getText());
        four = 2* Integer.parseInt(fours.getText());
        six = 3* Integer.parseInt(sixes.getText());
        
        wicket = 25* Integer.parseInt(wickets.getText());
        over = Integer.parseInt(overs.getText());
        maiden = 10* Integer.parseInt(maidens.getText());
        give= Integer.parseInt(given.getText());
        
        catche = 5* Integer.parseInt(catches.getText());
        runout = 10* Integer.parseInt(runouts.getText());
        stumping = 20* Integer.parseInt(stumpings.getText());
                        
        if(ball!=0)
        {
            strike=(run/ball)*100;
        }
        else
        {   
            strike=0;
        }
        
        if(over!=0)
        {
            economy=(give/over);
        }
        else
        {
            economy=0;
        }
        
        if(run==0)
        runbonus= -5;
        else
        if(run>=30 && run<50)
        runbonus=5;
        else
        if(run>=50 && run<100)
        runbonus=10;
        else
        if(run>=100)
        runbonus=20;
 
        if(wicket==3)
        wicketbonus=10;
        else
        if(wicket==5)
        wicketbonus=20;

        if(strike>=100 && strike<150)
        strikebonus=5;
        else
        if(strike>=150 && strike<200)
        strikebonus=10;
        else
        if(strike>=200)
        strikebonus=20;    

        sum = run + four + six + wicket + (2*over) + catche + maiden + runout + stumping + runbonus + wicketbonus + strikebonus;
        
        strikerate.setText(strike+"");
        economyrate.setText(economy+"");

        total.setText(sum+"");
        
        
        }
        catch(Exception e)
        {
        System.out.println(e);
        }
        
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void runoutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runoutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runoutsActionPerformed

    private void ballsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballsActionPerformed

    private void foursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foursActionPerformed

    private void oversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oversActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oversActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
globaltotal=Integer.parseInt (total.getText());
        points pt=new points();
        pt.setVisible(true);
this.dispose();        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(points_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(points_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(points_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(points_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new points_calculation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balls;
    private javax.swing.JTextField catches;
    private javax.swing.JLabel economyrate;
    private javax.swing.JTextField fours;
    private javax.swing.JTextField given;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maidens;
    private javax.swing.JTextField overs;
    private javax.swing.JTextField runouts;
    private javax.swing.JTextField runs;
    private javax.swing.JTextField sixes;
    private javax.swing.JLabel strikerate;
    private javax.swing.JTextField stumpings;
    private javax.swing.JLabel total;
    private javax.swing.JTextField wickets;
    // End of variables declaration//GEN-END:variables
}
