/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gesture;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class past_history extends javax.swing.JFrame {

Connection con=null;
Statement stmt=null;
ResultSet rs=null;

    /**
     * Creates new form past_history
     */
    public past_history() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pasthistory = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 580));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Homoarakhn", 1, 24)); // NOI18N
        jLabel1.setText("Tell us about your Past History");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(168, 23, 716, 59);

        pasthistory.setColumns(20);
        pasthistory.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        pasthistory.setRows(5);
        pasthistory.setText("None");
        jScrollPane1.setViewportView(pasthistory);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 152, 874, 210);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel2.setText("Do you want to mention any incident or expierence that has affected you emotionally or mentally to a large extent? (if any)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 874, 41);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gesture/Next-Button.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 419, 190, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gesture/Care-Your-Depression-o.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1020, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
       {

           
        Class.forName("java.sql.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localHost/gesture","root","1234");
        System.out.println("connectivity done");
        con.createStatement();
        
        String q = "select curdate()+0 from dual;";
          stmt=con.createStatement();
          rs=stmt.executeQuery(q);
       
          rs.first();
          int curdate = rs.getInt(1);

        String q1="select name from user_table where u_id='"+homepage.uid+"';";    
        rs=stmt.executeQuery(q1);
       
        rs.first();
        String name = rs.getString(1);
        
        String past=pasthistory.getText();
        System.out.println("name is"+ name + "\n"+"past is " +past);
       // String remedy="";
        
      String q2="insert into past_table values("+'\"'+homepage.uid+'\"'+","+'\"'+name+'\"'+","+'\"'+past+'\"'+","+answers.dq+","+answers.dv+","+analysis.davg+","+'\"'+curdate+'\"'+");";
     stmt.executeUpdate(q2);
        
answers a = new answers();
a.setVisible(true);
this.dispose();
       
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter some text!!");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(past_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(past_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(past_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(past_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new past_history().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pasthistory;
    // End of variables declaration//GEN-END:variables
}
