package gesture;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.Timer;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Splash.java
 *
 * Created on Dec 23, 2010, 1:07:06 PM
 */

/**
 *
 * @author user
 */
public class Splash extends javax.swing.JFrame {
static int count = 0;
    public static String a;
Statement stmt;
Connection con=null;
ResultSet rs=null;
int r;
int j1,i;
Timer t=new Timer(100,new ActionListener(){
public void actionPerformed(ActionEvent e){

      int r=p1.getValue();
p1.setValue(r+1);
 ++i;
if (i >= 1 && i<=10)
    lbl.setVisible(true);
else
    if(i >= 11 && i<= 20){
     lbl.setVisible(false);
       lbl1.setText("Checking parameters..."); }
        else
    if(i>= 21 && i<= 30)
     lbl.setVisible(true);   
        else
    if(i>= 31 && i<= 40){
     lbl.setVisible(false);
        lbl1.setText("Loading modules..."); }
        else
    if(i>= 41 && i<= 50)
 lbl.setVisible(true);
           else
    if(i>= 51 && i<= 60){
     lbl.setVisible(false);
 lbl1.setText("Connecting to MOOD INDEGO..."); }
     else
    if(i>= 61 && i<= 70)
     lbl.setVisible(true);
    else
    if(i>= 71 && i<= 80){
     lbl.setVisible(false);
      lbl1.setText("Waiting for reply..."); }
    else
    if(i>= 81 && i<= 90) 
        lbl.setVisible(true);
    else
    if(i>= 91 && i<= 100){
            lbl.setVisible(false);
       lbl1.setText("Authenticated..."); }
    else
    if (i >=101  && i<=110)
    lbl.setVisible(true);
    else
    if(i >= 111 && i<= 120)
     lbl.setVisible(false);
        else
    if(i>= 121 && i<= 130)
     lbl.setVisible(true);
        else
    if(i>= 131 && i<= 140)
     lbl.setVisible(false);
        else
    if(i>= 141 && i<= 150)
     lbl.setVisible(true);

    
 } } );
    

    /** Creates new form Splash */
    public Splash() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        p1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(550, 300));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl1.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl1);
        lbl1.setBounds(280, 190, 270, 30);

        lbl.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("LOADING.....");
        getContentPane().add(lbl);
        lbl.setBounds(310, 240, 210, 20);

        p1.setForeground(new java.awt.Color(255, 0, 0));
        p1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p1StateChanged(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(10, 260, 530, 14);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 70, 110);

        j.setOpaque(true);
        getContentPane().add(j);
        j.setBounds(0, 0, 400, 0);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gesture/take-off-the-mask.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 560, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
t.start();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void p1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p1StateChanged
              Splash p = new Splash();
        if(p1.getValue()==100){
            t.stop();
            this.dispose();
            p.setVisible(false);}
        if (p1.getValue()==100){
           homepage a = new homepage();
            a.setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_p1StateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JProgressBar p1;
    // End of variables declaration//GEN-END:variables

}
